#! /usr/bin/env python
import sys

def find_domains(data):
    stack = []
    domains = []
    begin = 0

    for i in range(len(data[0])):
        if data[1][i] == '(':
            stack.append(i)
        elif data[1][i] == ')':
            stack.pop()
            if len(stack) == 0:
                domains.append((begin, i))
                begin = i + 1
    if set(data[1][begin:i+1]) == {'.'}:
        domains[-1] = (domains[-1][0], i)
    return domains


if __name__ == '__main__':
    with open(sys.argv[1]) as f:
        wt = f.readlines()
        wt[0] = wt[0].strip()
        wt[1] = wt[1].split()[0]
    with open(sys.argv[2]) as f:
        mut = f.readlines()
        mut[0] = mut[0].strip()
        mut[-1] = mut[-1].split()[0]

    domains_wt = find_domains(wt)
    domains_mut = find_domains(mut)

    for begin, end in domains_wt:
        with open(f"wt-dotbracket-{begin}-{end}.txt", "w") as f:
            f.write(f"{wt[0][begin:end+1]}\n{wt[1][begin:end+1]}\n")

    for begin, end in domains_mut:
        with open(f"mut-dotbracket-{begin}-{end}.txt", "w") as f:
            f.write(f"{mut[0][begin:end+1]}\n{mut[1][begin:end+1]}\n")
