#! /usr/bin/env python
import sys

if __name__ == '__main__':
    with open(sys.argv[1]) as f:
        wt = f.readlines()
        wt[0] = wt[0].strip()
        wt[1] = wt[1].split()[0]
    with open(sys.argv[2]) as f:
        mut = f.readlines()
        mut[0] = mut[0].strip()
        mut[-1] = mut[-1].split()[0]

    annot_wt = ["0 0 1 setrgbcolor"]
    annot_mut = ["1 0 0 setrgbcolor"]

    i = 0
    j = 0
    min_i, max_i = None, None
    min_j, max_j = None, None

    while i < len(wt[0]) and j < len(mut[0]):
        if wt[0][i] != mut[0][j]:
            if len(wt[0]) > len(mut[0]):
                min_i = min(min_i or i, i)
                max_i = max(max_i or i, i)
                annot_wt.append(f"{i+1} cmark")
                i += 1
            elif len(wt[0]) < len(mut[0]):
                min_j = min(min_j or j, j)
                max_j = max(max_j or j, j)
                annot_mut.append(f"{j+1} cmark")
                j += 1
            else:
                min_i = min(min_i or i, i)
                max_i = max(max_i or i, i)
                min_j = min(min_j or j, j)
                max_j = max(max_j or j, j)
                annot_wt.append(f"{i+1} cmark")
                annot_mut.append(f"{j+1} cmark")
                i += 1
                j += 1
            continue
        if wt[1][i] == mut[1][j]:
            i += 1
            j += 1
            continue
        else:
            min_i = min(min_i or i, i)
            max_i = max(max_i or i, i)
            min_j = min(min_j or j, j)
            max_j = max(max_j or j, j)
            annot_wt.append(f"{i+1} cmark")
            annot_mut.append(f"{j+1} cmark")
            i += 1
            j += 1
            continue

    if min_i is not None and max_i is not None and min_i != max_i:
        annot_wt.append(f"{min_i+1} {max_i+1} 3 0 0 1 omark")
    annot_wt.append("drawbases")

    if min_j is not None and max_j is not None and min_j != max_j:
        annot_mut.append(f"{min_j+1} {max_j+1} 3 1 0 0 omark")
    annot_mut.append("drawbases")

    print(' '.join(annot_wt))
    print(' '.join(annot_mut))
